name: 发布文档

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 6.0.2
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: pnpm i
      - run: git config --global user.email "18826255448@163.com" && git config --global user.name "藤原托漆" && pnpm deploy
